using PauliOperators
using UnitaryPruning
using Printf
using IterTools
using LinearAlgebra

"""
  In this tests we will implement a complete evaluation of the energy for XXZ Heisenberg model using an ADAPT-VQE 
  approach based on PP, we follow the original strategy of Grimsley et al.
  https://www.nature.com/articles/s41467-019-10988-2/figures/1

  To this end we consider the following steps:
    1) Define the molecule and run an SCF to get the integrals and Qubit Hamiltonian
    2) Define the operrator pool consisting on 1 and 2 body qubit excitation operators
    3) Compute the gradients of each operator in the pool with respect to the initial state
    4) Select the operator with the largest gradient and add it to the ansatz
    5) Optimize the ansatz parameters to minimize the energy
    6) Repeat from step 3 until convergence is reached

   In the Heisenberg picture, the Hamiltonian is evolved as:
       H' = U† H U
   where U = ∏_j exp(i θ_j G_j) is the unitary operator generated by the ansatz operators G_j and parameters θ_j.
   Our generators are the operators in the pool, and the parameters are the angles associated to each operator.
    
   The energy is then computed as:
         E = <ψ| H' |ψ>
    where |ψ> is the initial state (e.g., Hartree-Fock state).

   However, the gradients are computed as:
         dE/dθ_k = <ψ| [i G_k, H'] |ψ>
    which can be evaluated using the commutator of the generator G_k with the evolved Hamiltonian H'.
"""

# # # # # # # # # F U N C T I O N S # # # # # # # # # # #
"""
  The following functions implement standard pools (GSD for fermions)
  Part of them has been taken or based from Kyle Sherbert's ADAPT.jl package:
  https://github.com/kmsherbertvt/ADAPT.jl/blob/main/src/base/pools.jl

  Qubit excitation pool is based on: https://www.nature.com/articles/s42005-021-00730-0

  # N is the number of qubits
    # i,j are the qubits indices as defined Yordanov et. al. 2021
    # Note that Yordanov's unitaries are defined as `exp(iθG)` rather than `exp(-iθG)`,
    # so variational parameters will be off by a sign.
    # Returns 
    # -PauliOperators.PauliSum{N} : The qubit excitation operator as a PauliSum
    # Note that all pauli terms in any single qubit excitation operator commute, 
    #so we can return a single PauliSum
"""
function qubitexcitation(n::Int, i::Int, k::Int)
    return 0.5 .* [Pauli(n, X=[i], Y=[k]),
                   -Pauli(n, X=[k], Y=[i])]
end

function qubitexcitation(n::Int, i::Int, j::Int, k::Int, l::Int)
        return (1/8) .* [Pauli(n; X=[i,k,l], Y=[j]),
                         Pauli(n; X=[j,k,l], Y=[i]),
                         Pauli(n; X=[l], Y=[i,j,k]),
                         Pauli(n; X=[k], Y=[i,j,l]),
                         -Pauli(n; X=[i,j,l], Y=[k]),
                         -Pauli(n; X=[i,j,k], Y=[l]),
                         -Pauli(n; X=[j], Y=[i,k,l]),
                         -Pauli(n; X=[i], Y=[j,k,l])]
    end

"""                
    qubitexcitationpool(n_system::Int)
          
    The number of singles excitations = (n 2), and the doubles = 3*(n 4).
            
   # Parameters
    - `n_system`: Number of qubits in the system

    # Returns
    - `pool`: the qubit-excitation-based pool as defined in Communications Physics 4, 1 (2021).
    - `target_and_source`: Dict mapping each pool operator to the target and source orbitals involved in the excitation. 
"""               
function qubitexcitationpool(n_system::Int)
    pool = Vector{Pauli{n_system}}()
    coeffs = Vector{Float64}()
    #target_and_source = Dict{PauliSum{n_system}, Vector{Vector{Int64}}}()
                            
    for i in 1:n_system
        for j in i+1:n_system
            # singles excitations
            singles = qubitexcitation(n_system, i, j)
            for op in singles
#                println("Operator in Single excitation")
#                display(op)
                push!(pool, op)
                push!(coeffs, 1.0) # Initial coefficient
            end
#            target_and_source[singles] = [[i,j]]

            # doubles excitations
            for k in j+1:n_system
                for l in k+1:n_system
                    target_pair = [i,j]; source_pair = [k,l]
                    doubles = qubitexcitation(n_system, target_pair[1], target_pair[2], source_pair[1], source_pair[2])
                    for op in doubles
#                        println("Operator in Double excitation")
#                        display(op)
                        push!(pool, op)
                        push!(coeffs, 1.0) # Initial coefficient
                    end
#                    arget_and_source[doubles] = [target_pair,source_pair]

                    target_pair = [i,k]; source_pair = [j,l]
                    doubles = qubitexcitation(n_system, target_pair[1], target_pair[2], source_pair[1], source_pair[2])
                    for op in doubles
#                        println("Operator in Double excitation")
#                        display(op)
                        push!(pool, op)
                        push!(coeffs, 1.0) # Initial coefficient
                    end
#                    target_and_source[doubles] = [target_pair,source_pair]
               
                    target_pair = [j,k]; source_pair = [i,l]     
                    doubles = qubitexcitation(n_system, target_pair[1], target_pair[2], source_pair[1], source_pair[2])
                    for op in doubles
#                        println("Operator in Double excitation")
#                        display(op)
                        push!(pool, op)
                        push!(coeffs, 1.0) # Initial coefficient
                    end
#                    target_and_source[doubles] = [target_pair,source_pair]

                    end
                end
            end
        end
        return pool,coeffs #, target_and_source                                            
    end

"""
 The following function computes the gradients of the energy computed as the expectation value of a commutator
  < [H, A] > with respect to a state |psi>
  H -> Hamiltonian as a PauliSum
  A -> Operator as a Pauli
  psi -> State as a Ket
"""
function energy_gradient(H::PauliSum{N}, A::Pauli{N}, psi::Ket) where N
    # collect our results here...
    expval = zero(ComplexF64)
    commutator = PauliSum(N)

    for (h, c) in H
        if !PauliOperators.commute(h, PauliBasis(A))
            comm = 2 * h * A # This includes the correct ±i phase
            #println("Commutator of $h and $A is: ")
            #display(comm)
            sum!(commutator, c * d * comm)
        end
    end

    #println("The full commutator is: ")
    #display(commutator)
    #println("- - - - - - - - - - - - - ")
    #println("Now computing the expectation value of the commutator...")
    for (oi, coeff) in commutator
        expval += coeff * PauliOperators.expectation_value(oi, psi)
   #     println("Expectation value of the commutator is: $expval")
    end
    return imag(expval)
end


"""
 "Cost function" for the ADAPT-VQE with PP
  This function computes the energy expectation value of the evolved Hamiltonian with respect to the initial state  
"""
function cost_energy(Op::PauliSum{N}, coeffs::Vector{Float64},ket::Ket) where N
   e = PauliOperators.expectation_value(Op, ket)
  return e
end


#
# # # # # # Main program # # # # # #
#

# 1) Define the molecule and run an SCF to get the integrals and Qubit Hamiltonian
println("= = = = = = = = ADAPT-VQE with PP = = = = = = = ")
println("Molecule and Hamiltonian definition")
d = 0.74
N_qubits = 4
o = Pauli(N_qubits, Z=[1])
H_terms, H_coeffs = UnitaryPruning.heisenberg_1D(o; Jx=1.0, Jy=1.0, Jz=1.0, k=1)
ket = Ket(N_qubits, 0) #All-zero state |00 ... 00⟩

# Display the initial state
println("Initial state |ψ_0⟩:")
display(ket)

H_op = PauliSum(N_qubits)
for (p,c) in zip(H_terms, H_coeffs)
    global H_op += c * p
end

println("Hamiltonian as PauliSum:")
display(H_op)
rhf_energy = PauliOperators.expectation_value(H_op, ket)
println("HF Energy is: $rhf_energy")
println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# 2) Define the operator pool consisting on 1 and 2 body qubit excitation operators

pool, pool_coeffs = qubitexcitationpool(N_qubits)
println("Pool generated with $(length(pool)) operators.")
println(typeof(pool))
for p in pool
    display(p)
end

println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# 3) Initialize and Compute the gradients of each operator in the pool with respect to the initial state
cycle = 0
e0 = PauliOperators.expectation_value(H_op, ket)
println(" Cycle: $cycle | Energy: $e0 ")


println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# 4) Select the operator with the largest gradient and add it to the ansatz
# Measure gradients
#Create a dictionary to store the gradients and associated operators
gradients = Dict{Any, ComplexF64}()

for p in pool
    grad = energy_gradient(H_op, p, ket)
    gradients[p] = grad # Store the gradient associated to the operator
    #println("Gradient for operator $p is: $grad")
end

sorted_grads = sort(collect(gradients), by=x->-abs(x[2])) # Sort by absolute value of the gradient
max_op, max_grad = sorted_grads[1] # Get the operator with the largest gradient
println("Operator with the largest gradient: $max_grad")
display(max_op)

push!(pool_coeffs, 1.0) # Initial coefficient for the selected operator
push!(pool, max_op)

# Perform evolution of the Hamiltonian with the selected operator
# This must be equivalent to growing the ansatz with the selected operator
evol_op = UnitaryPruning.bfs_evolution_vqe(pool, pool_coeffs, H_op, thresh=1e-6)
println("Evolved Hamiltonian after Unitary Pruning:")
display(evol_op)

println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# Check expectation value and convergence
e1 = PauliOperators.expectation_value(evol_op, ket)
cycle += 1
println(" Cycle: $cycle | Energy: $e1 ")

# 5) Re-Optimize all parameters to minimize the energy

# PENDING: Implement Optimization routines

# 6) Repeat from step 3 until convergence is reached

##############
#NEXT CYCLE
gradients = Dict{Any, ComplexF64}()

for p in pool
    grad = energy_gradient(evol_op, p, ket)
    gradients[p] = grad # Store the gradient associated to the operator
    #println("Gradient for operator $p is: $grad")
end

sorted_grads = sort(collect(gradients), by=x->-abs(x[2])) # Sort by absolute value of the gradient
max_op, max_grad = sorted_grads[1] # Get the operator with the largest gradient
println("Operator with the largest gradient: $max_grad")
display(max_op)

push!(pool_coeffs, 1.0) # Initial coefficient for the selected operator
push!(pool, max_op)

# Perform evolution of the Hamiltonian with the selected operator
# This must be equivalent to growing the ansatz with the selected operator
evol_op = UnitaryPruning.bfs_evolution_vqe(pool, pool_coeffs, evol_op, thresh=1e-6)
println("Evolved Hamiltonian after Unitary Pruning:")
display(evol_op)

println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# Check expectation value and convergence
e1 = PauliOperators.expectation_value(evol_op, ket)
cycle += 1
println(" Cycle: $cycle | Energy: $e1 ")

##############
#NEXT CYCLE
gradients = Dict{Any, ComplexF64}()

for p in pool
    grad = energy_gradient(evol_op, p, ket)
    gradients[p] = grad # Store the gradient associated to the operator
    #println("Gradient for operator $p is: $grad")
end

sorted_grads = sort(collect(gradients), by=x->-abs(x[2])) # Sort by absolute value of the gradient
max_op, max_grad = sorted_grads[1] # Get the operator with the largest gradient
println("Operator with the largest gradient: $max_grad")
display(max_op)

push!(pool_coeffs, 1.0) # Initial coefficient for the selected operator
push!(pool, max_op)

# Perform evolution of the Hamiltonian with the selected operator
# This must be equivalent to growing the ansatz with the selected operator
evol_op = UnitaryPruning.bfs_evolution_vqe(pool, pool_coeffs, evol_op, thresh=1e-6)
println("Evolved Hamiltonian after Unitary Pruning:")
display(evol_op)

println("- - - - - - - - - - - - - - - - - - - - - - - - ")
# Check expectation value and convergence
e1 = PauliOperators.expectation_value(evol_op, ket)
cycle += 1
println(" Cycle: $cycle | Energy: $e1 ")